### PR TITLE
Polymer2

### PR DESCRIPTION
**Pull request by alexanderson1993**
## Changes
* Modified the `<content>` tag to be `<slot>` as explained in the [Polymer Hybrid Element Guide](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements#working-with-dom)
* Used `this.querySelector()` instead of `this.$.` to access internal elements (where necessary)

## To-Dos
- [ ] Tests
- [ ] Update demo
- [ ] Update documentation & README
- [ ] Increment bower.json version

### CODE REVIEW

**Comment by alexanderson1993** [comment]
Is there any documentation for how to run tests on a local machine?

**Comment by skye2k2** [comment]
Sorry, we missed updating the docs in this repo. Should be the same as here: https://github.com/fs-webdev/fs-person-card#running-tests

**Comment by alexanderson1993** [comment]
Odd. For some reason, the tests seem to hang after test 16, even on a freshly-pulled master branch. Any idea why that would be?

**Comment by skye2k2** [comment]
Huh. Passing for me locally on a clean build and in Travis CI: https://travis-ci.org/fs-webdev/dialog-el/builds

**Comment by alexanderson1993** [comment]
Weird. I did a clean clone and it's working just fine. I must have bower dependency mismatch. Thanks for the response.

**Pull request merged**
