### PR TITLE
Add "allowArrowChange" property to specify if smart positioning is used

### PR DESCRIPTION
**Pull request by Norman-Amy**
Unless this property is included, the default behavior is that smart positioning will not change the specified arrow direction.

### CODE REVIEW

**Comment by crowtherdr** [comment]
Ok. Here is what I think is the behavior for this:
- If 'allowArrowChange' is present or true, dialog-el will determine the position for the arrow. Will it obey 'arrowDirection' if that is possible?
- If 'allowArrowChange' is absent or false, dialog-el will always position the arrow according to 'arrowDirection'. What if 'arrowDirection' is not present?

**Comment by crowtherdr** [comment]
And the default for 'allowArrowChange' is false? Does this mean that by default dialog-el will not try to position itself automatically?

**Comment by Norman-Amy** [comment]
Correct. The default is to not have it auto-position. 

The arrow-direction is used as the default starting direction when auto-positioning the dialog. It changes only if there isn't enough room for it in that direction. 

Without 'allowArrowChange' the arrow-direction is the only direction and it will not change automatically.

If arrow-direction is left off for whatever reason, then 'allowArrowDirection' changes nothing. The dialog acts as a dialog with no arrow and no auto-positioning.

**Comment by crowtherdr** [comment]
Great explanation. I suggest putting it in the Readme file.

**Comment by crowtherdr** [comment]
Do existing unit tests cover this?

**Comment by Norman-Amy** [comment]
Well, I don't know. The unit tests were written by Josh and I'm afraid to touch them, because they aren't sorted logically to me. I guess that's no excuse though. I'll need to add some for the new function I'm working on to close other dialogs, so I can add some in then.

**Pull request merged**
